"""The Doctor Lives: persistent renderer-neutral Pretorius cognition."""

from .causal_audit import AuditIntervention, CausalAuditHarness
from .awareness import AwarenessCandidate, AwarenessDecision, AwarenessPolicy, AwarenessRouter
from .recollection import (
    MemoryTrace,
    ProtectedEvidenceRef,
    ReconstructionConfig,
    RecollectionCandidate,
    RetrievalEpisode,
    TraceDetail,
    reconstruct_recollection,
)
from .chassis import PretoriusBrainPort
from .cognition import PretoriusBrain
from .models import CognitiveView, Experience, Provenance, RenderRequest, ViewItem
from .phenomenology import (
    AwarenessLevel,
    CertaintyBand,
    IntensityBand,
    ObjectiveProvenance,
    PhenomenalEvent,
    PhenomenalMode,
    PrivacyState,
    Recollection,
    SubjectiveSourceAttribution,
    SubjectiveSourceKind,
    VividnessBand,
)
from .projection import (
    BodilySignal,
    PhenomenalLeakError,
    ProjectionContext,
    assert_subject_text_safe,
    implementation_leaks,
    project_appraisal_feeling,
    project_bodily_sensation,
    project_commitment,
    project_concern,
    project_impulse,
    project_relationship_feeling,
    project_uncertainty,
)

__all__ = [
    "PretoriusBrain",
    "CausalAuditHarness",
    "AuditIntervention",
    "PretoriusBrainPort",
    "Experience",
    "Provenance",
    "ViewItem",
    "CognitiveView",
    "RenderRequest",
    "PhenomenalMode",
    "AwarenessLevel",
    "PrivacyState",
    "SubjectiveSourceKind",
    "CertaintyBand",
    "VividnessBand",
    "IntensityBand",
    "ObjectiveProvenance",
    "SubjectiveSourceAttribution",
    "PhenomenalEvent",
    "Recollection",
    "ProjectionContext",
    "BodilySignal",
    "PhenomenalLeakError",
    "implementation_leaks",
    "assert_subject_text_safe",
    "project_bodily_sensation",
    "project_appraisal_feeling",
    "project_impulse",
    "project_uncertainty",
    "project_relationship_feeling",
    "project_concern",
    "project_commitment",
    "AwarenessCandidate",
    "AwarenessDecision",
    "AwarenessPolicy",
    "AwarenessRouter",
    "ProtectedEvidenceRef",
    "TraceDetail",
    "MemoryTrace",
    "RetrievalEpisode",
    "ReconstructionConfig",
    "RecollectionCandidate",
    "reconstruct_recollection",
]
